# Generated by Django 4.2.16 on 2024-11-03 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0002_hurdlesrunscore_quizdetail_quizquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hurdlesrunscore',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='hurdlesrunscore',
            name='date_played',
        ),
        migrations.RemoveField(
            model_name='hurdlesrunscore',
            name='high_score',
        ),
    ]
